import re

# INPUTS
# You usually will receive the domain list to block on a PDF file. Save it to a excel
# file and clean undesired data that came from the PDF.

# The file with a list of domains unformated (eg. many domains on the same line, 
# or Texts that aren't domains - don't have a dot ".")
unformatedDomainList = './domains.txt'

# The output file generated by this script in which should be used by add-domains-to-block.py
outputBlacklistFile = './domainsToBlock.txt'

def readFromInputFile(inputFile):
    domainList = list()
    file = open(inputFile, 'r')
    # Read line by line
    for line in file:
        # Split each word separated by a space character
        for word in line.split(" "):
            # Test if the line is a domain (has a dot ".")
            domain = re.findall(r'\.', word.lower())
            # if it is not, just skip
            if not domain:
                continue
            # if it is a domain, add to a filtered domain list
            domainList.append(word.split()[0])
    return domainList

def writeToBlacklistFile(domainList, outputBlacklistFile):
    file = open(outputBlacklistFile, 'w')
    for domain in domainList:
        file.write('{0}\n'.format(domain))
    file.close()
    print("Writed {} domains to {}".format(len(domainList), outputBlacklistFile))

domains = readFromInputFile(unformatedDomainList)
writeToBlacklistFile(domains, outputBlacklistFile)